import type { TopicDefinition } from './types'

export const topicTaxonomy: TopicDefinition[] = [
  {
    id: 'ischemic-heart-disease',
    name: 'Ischemic heart disease',
    system: 'Cardiovascular',
    aliases: ['myocardial infarction', 'acute coronary syndrome', 'stable angina', 'unstable angina', 'troponin', 'st elevation', 'plaque rupture'],
    relevance: 1,
    action: 'Review coronary perfusion, ECG localization, biomarkers, and acute management pathways.',
  },
  {
    id: 'heart-failure',
    name: 'Heart failure & hemodynamics',
    system: 'Cardiovascular',
    aliases: ['heart failure', 'ejection fraction', 'preload', 'afterload', 'cardiac output', 'frank starling', 'pulmonary edema'],
    relevance: 0.95,
    action: 'Connect pressure-volume loops with systolic and diastolic failure treatments.',
  },
  {
    id: 'valvular-disease',
    name: 'Valvular heart disease',
    system: 'Cardiovascular',
    aliases: ['aortic stenosis', 'aortic regurgitation', 'mitral stenosis', 'mitral regurgitation', 'murmur', 'valvular disease'],
    relevance: 0.85,
    action: 'Practice murmur timing, maneuvers, pressure changes, and classic presentations.',
  },
  {
    id: 'acid-base',
    name: 'Acid–base disorders',
    system: 'Renal',
    aliases: ['metabolic acidosis', 'metabolic alkalosis', 'respiratory acidosis', 'respiratory alkalosis', 'anion gap', 'winter formula', 'acid base'],
    relevance: 1,
    action: 'Work mixed-disorder cases using pH, compensation rules, and the anion gap.',
  },
  {
    id: 'acute-kidney-injury',
    name: 'Acute kidney injury',
    system: 'Renal',
    aliases: ['acute kidney injury', 'prerenal azotemia', 'acute tubular necrosis', 'fractional excretion of sodium', 'muddy brown casts', 'creatinine'],
    relevance: 0.95,
    action: 'Compare prerenal, intrinsic, and postrenal patterns with urine indices.',
  },
  {
    id: 'glomerular-disease',
    name: 'Glomerular disease',
    system: 'Renal',
    aliases: ['nephritic syndrome', 'nephrotic syndrome', 'glomerulonephritis', 'proteinuria', 'red blood cell casts', 'minimal change disease'],
    relevance: 0.85,
    action: 'Build a pattern table for nephritic and nephrotic etiologies and biopsy findings.',
  },
  {
    id: 'diabetes-emergencies',
    name: 'Diabetes & acute complications',
    system: 'Endocrine',
    aliases: ['diabetic ketoacidosis', 'hyperosmolar hyperglycemic state', 'insulin', 'c peptide', 'ketone bodies', 'diabetes mellitus'],
    relevance: 1,
    action: 'Sequence fluids, potassium, and insulin while reviewing diabetes pathophysiology.',
  },
  {
    id: 'thyroid-disorders',
    name: 'Thyroid disorders',
    system: 'Endocrine',
    aliases: ['hyperthyroidism', 'hypothyroidism', 'graves disease', 'hashimoto', 'thyroid stimulating hormone', 'thyroid storm'],
    relevance: 0.85,
    action: 'Review thyroid feedback patterns, antibodies, drug mechanisms, and emergencies.',
  },
  {
    id: 'adrenal-disorders',
    name: 'Adrenal disorders',
    system: 'Endocrine',
    aliases: ['cushing syndrome', 'addison disease', 'primary hyperaldosteronism', 'pheochromocytoma', 'cortisol', 'aldosterone'],
    relevance: 0.8,
    action: 'Map hormone patterns to localization tests and characteristic clinical findings.',
  },
  {
    id: 'gas-exchange',
    name: 'Gas exchange & V/Q',
    system: 'Pulmonary',
    aliases: ['ventilation perfusion', 'v q mismatch', 'a a gradient', 'hypoxemia', 'shunt', 'dead space', 'oxygen dissociation curve'],
    relevance: 1,
    action: 'Practice distinguishing V/Q mismatch, shunt, diffusion, and hypoventilation.',
  },
  {
    id: 'obstructive-lung-disease',
    name: 'Obstructive lung disease',
    system: 'Pulmonary',
    aliases: ['asthma', 'chronic obstructive pulmonary disease', 'emphysema', 'chronic bronchitis', 'fev1', 'obstructive lung disease'],
    relevance: 0.9,
    action: 'Compare spirometry, pathology, and stepwise pharmacologic management.',
  },
  {
    id: 'antimicrobial-therapy',
    name: 'Antimicrobial therapy',
    system: 'Infectious disease',
    aliases: ['beta lactam', 'vancomycin', 'aminoglycoside', 'macrolide', 'antibiotic resistance', 'empiric antibiotics', 'antimicrobial'],
    relevance: 0.95,
    action: 'Pair drug mechanisms and resistance patterns with empiric clinical choices.',
  },
  {
    id: 'hypersensitivity',
    name: 'Hypersensitivity reactions',
    system: 'Immunology',
    aliases: ['type i hypersensitivity', 'type ii hypersensitivity', 'type iii hypersensitivity', 'type iv hypersensitivity', 'anaphylaxis', 'immune complex'],
    relevance: 0.85,
    action: 'Organize reaction types by mediator, timing, mechanism, and classic disease.',
  },
  {
    id: 'cerebrovascular-disease',
    name: 'Cerebrovascular disease',
    system: 'Neurology',
    aliases: ['ischemic stroke', 'hemorrhagic stroke', 'middle cerebral artery', 'anterior cerebral artery', 'posterior cerebral artery', 'thrombolysis', 'broca aphasia'],
    relevance: 1,
    action: 'Localize vascular territories and rehearse acute stroke eligibility decisions.',
  },
  {
    id: 'pharmacokinetics',
    name: 'Pharmacokinetics',
    system: 'Pharmacology',
    aliases: ['volume of distribution', 'clearance', 'half life', 'steady state', 'loading dose', 'maintenance dose', 'first order kinetics'],
    relevance: 0.9,
    action: 'Solve dose, clearance, half-life, and steady-state calculations from first principles.',
  },
  {
    id: 'gram-positive-bacteria',
    name: 'Gram-positive bacteria',
    system: 'Microbiology',
    aliases: ['staphylococcus aureus', 'streptococcus pneumoniae', 'streptococcus pyogenes', 'enterococcus', 'gram positive cocci', 'catalase positive', 'coagulase positive'],
    relevance: 0.85,
    action: 'Rebuild organism identification using morphology, tests, virulence, and treatment.',
  },
  {
    id: 'medical-ethics',
    name: 'Medical ethics & communication',
    system: 'Behavioral science',
    aliases: ['informed consent', 'decision making capacity', 'surrogate decision maker', 'confidentiality', 'advance directive', 'breaking bad news'],
    relevance: 0.8,
    action: 'Practice scenario-based decisions using capacity, autonomy, and confidentiality rules.',
  },
  {
    id: 'osteopathic-principles',
    name: 'Osteopathic principles',
    system: 'OMM',
    aliases: ['somatic dysfunction', 'chapman point', 'viscerosomatic reflex', 'muscle energy', 'counterstrain', 'cranial rhythmic impulse'],
    relevance: 0.85,
    action: 'Review diagnosis landmarks, viscerosomatic levels, and treatment positioning.',
  },
]
